const words = `That is because computer chips are the foundations of the digital economy and national security. Cars have become computers on wheels. Banks are computers that move money. Armies fight with silicon as well as steel (see article). Firms from America and its allies, such as South Korea and Taiwan, dominate the most advanced areas of the industry. China, by contrast, remains reliant on the outside world for supplies of high-end chips. It spends more on semiconductor imports than it does on oil. The list of the top 15 semiconductor firms by sales does not contain a single Chinese name.
Well before Mr Trump arrived on the scene, China made plain its intention to catch up. In 2014 the government in Beijing announced a 1trn yuan ($150bn) investment fund to improve its domestic industry. Semiconductors feature prominently in “Made in China 2025”, a national development plan issued in 2015. 
China’s ambitions to create a cutting-edge industry worried Mr Trump’s predecessor. Barack Obama blocked Intel from selling some of its whizziest chips to China in 2015, and stymied the acquisition of a German chipmaker by a Chinese firm in 2016. A White House report before he left office recommended taking action against Chinese subsidies and forced technology transfer. Other countries are alarmed, too. Taiwan and South Korea have policies to stop purchases of domestic chip firms by Chinese ones and to dam flows of intellectual property.
Although the chip battle may have pre-dated Mr Trump, his presidency has intensified it. He has made a national champion of Qualcomm, blocking a bid for it from a Singaporean firm for fear of Chinese competition. Earlier this year an export ban on selling American chips and software to zte, a Chinese telecoms firm in breach of sanctions, brought it to the brink of bankruptcy within days. Startled by the looming harm, and (he says) swayed by appeals from Mr Xi, Mr Trump swiftly backtracked.
Two things have changed. First, America has realised that its edge in technology gives it power over China. It has imposed export controls that affect on Fujian Jinhua, another Chinese firm accused of stealing secrets, and the White House is mulling broader bans on emerging technologies. Second, China’s incentives to become self-reliant in semiconductors have rocketed. After zte, Mr Xi talked up core technologies. Its tech giants are on board: Alibaba, Baidu and Huawei are ploughing money into making chips. And China has showed that it can hinder American firms. Earlier this year Qualcomm abandoned a bid for nxp, a Dutch firm, after foot-dragging by Chinese regulators.
Neither country’s interests are about to change. America has legitimate concerns about the national-security implications of being dependent on Chinese chips and vulnerable to Chinese hacking. China’s pretensions to being a superpower will look hollow as long as America can throttle its firms at will. China is destined to try to catch up; America is determined to stay ahead.
The hard question is over the lengths to which America should go. Protectionists in the White House would doubtless like to move the semiconductor supply chain to America. Good luck with that. The industry is a hymn to globalisation. One American firm has 16,000 suppliers, over half of them abroad. China is a huge market for many firms. Qualcomm makes two-thirds of its sales there. Trying to cleave the industry into two would hurt producers and consumers in America. And it would be a bluntly antagonistic act, which would make no distinction between unfair and genuine competition.
In the long run it may be futile, too. Today America has the edge over China in designing and making high-end chips. It can undoubtedly slow its rival. But China’s progress will be hard to stop. Just as Silicon Valley’s rise rested on the support of the American government, so China blends state and corporate resources in pursuit of its goals. It has incentive programmes to attract engineering talent from elsewhere, notably Taiwan. Firms like Huawei have a proven ability to innovate; blocking the flow of Intel chips in 2015 only spurred China on to develop its domestic supercomputing industry.
Moreover, China’s bid to become a global semiconductor powerhouse is propitiously timed. For decades the chip industry has been driven forward by Moore’s law, under which the capabilities of a chip of a given size double every two years. But Moore’s law is reaching its physical limits. As everyone jumps to new technologies, from quantum computing to specialised ai chips, China has a rare chance to catch up.
The right approach for America, therefore, has three strands. The first is to work with its allies in Europe and Asia to keep pushing back against unfair Chinese practices (such as forced tech transfer and intellectual-property theft) at the World Trade Organisation, and to screen out inward Chinese investments when security justifies it. The second is to foster domestic innovation. More government funding is already going into chip research; greater openness to talent is needed. And the third is to prepare for a world in which Chinese chips are more powerful and pervasive. That means, among other things, developing proper testing procedures to ensure the security of Chinese-made products; and tightening up on data-handling standards so that information is not being sprayed about so carelessly. Measures such as these will not make the headlines at the g20. But they will do more to shape the world in the years ahead.`

const wII = 'a because'

module.exports = {
    words,
    wII
}